name: espn-nfl-data-scraper
version: '0.1.0.0'
category: Haskell
author: Tyler Lentz
maintainer: tyler.cg.lentz@gmail.com
copyright: 2017 Tyler Lentz
license: BSD3
github: tlentz/espn-nfl-data-scraper
extra-source-files:
- README.md
dependencies:
- base
library:
  source-dirs: api
  exposed-modules:
  - Api.Lib
  - Api.Types
  - Api.Helper
  - Api.Server
  dependencies:
  - aeson
  - base
  - containers
  - elm-export
  - random
  - servant-server
  - stm
  - transformers
  - uuid
  - either-unwrap
  - MissingH
  - HTTP
  - http-client
  - text
  - hxt
  - http-types
  - string-conversions
  - pretty-simple
  - split
  - double-conversion
  - HandsomeSoup
  - transformers
  - http-conduit
  - mtl
  - resourcet
  - network
executables:
  backend:
    main: Main.hs
    source-dirs: backend
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - containers
    - http-client
    - pretty-simple
    - lucid
    - random
    - espn-nfl-data-scraper
    - servant-lucid
    - servant-server
    - stm
    - uuid
    - wai
    - warp
  code-generator:
    main: Main.hs
    source-dirs: code-generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - elm-export
    - servant-elm
    - espn-nfl-data-scraper
    - servant-server
    - text

tests:
  espn-nfl-data-scraper-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - espn-nfl-data-scraper
